services:
  kyutai-tts:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kyutai-tts-server

    # Enable GPU support
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    environment:
      - PYTHONUNBUFFERED=1
      - HF_HOME=/app/cache
      - TRANSFORMERS_CACHE=/app/cache

    volumes:
      # Mount cache directory to persist downloaded models
      - ./cache:/app/cache

    working_dir: /app

    ports:
      - "8000:8000"

    # Restart policy
    restart: unless-stopped